{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.0.1/sdk-1.0.1.module",
    "group": "com.accesspaysuite.mobilesdk",
    "module": "sdk",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "dev.icerock.moko",
          "module": "parcelize",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.tmapps",
          "module": "konnection",
          "version": {
            "requires": "1.1.10"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "cupertino-adaptive",
          "version": {
            "requires": "0.1.0-alpha04"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-iosArm64Main-1.0.1.klib",
          "url": "sdk-iosarm64-1.0.1.klib",
          "size": 1067618,
          "sha512": "0539b88b250657bf618d030b347d7b25008d126e09444b29876763db22e8b752781313568473b8ad596dc4b1a981c7b0ded38f6c2e049722ff362497119d4153",
          "sha256": "a787250ae2d30c6f5a0017934b1d7d683eb04e13dc97f7c4fd8b0e725dc3424f",
          "sha1": "c9b8238121b2f6c89f8a54e2654bdbae611f1b66",
          "md5": "4ca1d9697f3ca38d1703f734ca9adf44"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "sdk-iosarm64-1.0.1-sources.jar",
          "url": "sdk-iosarm64-1.0.1-sources.jar",
          "size": 151130,
          "sha512": "412602e0becdd9f6edaf772332e22377e5e986ec6d84dab86f3dcafd0e5073eff18e72601198ba3366b309988a4ef688a49945c8be63c60f5c06139f8af16abe",
          "sha256": "f18d25134f0de363c60eaeeec14d172d7e7017006e566fbf756761d390399d22",
          "sha1": "de0afe16c805303631b24f2cae2e3ff68cabe32c",
          "md5": "24579d6c15318d8e393bef83108cace3"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "dev.icerock.moko",
          "module": "parcelize",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.tmapps",
          "module": "konnection",
          "version": {
            "requires": "1.1.10"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "cupertino-adaptive",
          "version": {
            "requires": "0.1.0-alpha04"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.1.kotlin_resources.zip",
          "url": "sdk-iosarm64-1.0.1-kotlin_resources.kotlin_resources.zip",
          "size": 29587,
          "sha512": "93905f75246328b6dac11088253ac7e69e5994f1fafcc316a703623e8d9ad2141c0ae88406fcb990c6597114fc3800e879c95d7246576368829c0ebe1cfaa1a1",
          "sha256": "215731c82886b92490d8666a6a884fc2b04509d18cda8473b6cba529f1bbcf98",
          "sha1": "d54bdfba67734edb6aaf95ec82cd4b1f880f1ba4",
          "md5": "95992178386a7460a387f449a5b0b15f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "dev.icerock.moko",
          "module": "parcelize",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.tmapps",
          "module": "konnection",
          "version": {
            "requires": "1.1.10"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "cupertino-adaptive",
          "version": {
            "requires": "0.1.0-alpha04"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-iosarm64-1.0.1-metadata.jar",
          "url": "sdk-iosarm64-1.0.1-metadata.jar",
          "size": 18581,
          "sha512": "3a9ff453a88006f7887d193a5e3da9c79fe063b245959d93efaf51782afb8e82e7008f7af23d3139d8707d2091921befdf101bd7ae9184344655105708183dec",
          "sha256": "6d3073ec9b9cb4d3207b4ab14a706833f198085abb73e4399d9e648e3720d50a",
          "sha1": "7ce12f2b907b38b322303de9d12a26f7bd849dc5",
          "md5": "e1b922e981a95b87326479d7bda29516"
        }
      ]
    }
  ]
}
