{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.0.1-DEV-SNAPSHOT/sdk-1.0.1-DEV-SNAPSHOT.module",
    "group": "com.accesspaysuite.mobilesdk",
    "module": "sdk",
    "version": "1.0.1-DEV-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "dev.icerock.moko",
          "module": "parcelize",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.tmapps",
          "module": "konnection",
          "version": {
            "requires": "1.1.10"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "cupertino-adaptive",
          "version": {
            "requires": "0.1.0-alpha04"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-iosArm64Main-1.0.1-DEV-SNAPSHOT.klib",
          "url": "sdk-iosarm64-1.0.1-DEV-SNAPSHOT.klib",
          "size": 1054847,
          "sha512": "b46fae2905e7a16e25f418c134ccc00bcb000af7feae4033c745727d0ed9cf7854470728a1fa5ee6161bdba57bb0dc0ad72413f5124a17b3360ed2325607161e",
          "sha256": "cf313a883f2175b85c6dce507e61c0476de999a0f0e5c7cdb61b369a2d156dc6",
          "sha1": "08577425da371c77abae64e9a919880292481086",
          "md5": "b585993f93b4f9891d41a89e6f383bae"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "sdk-iosarm64-1.0.1-DEV-SNAPSHOT-sources.jar",
          "url": "sdk-iosarm64-1.0.1-DEV-SNAPSHOT-sources.jar",
          "size": 149294,
          "sha512": "821c9ce68378cc67be7b7a742c8337412ccc6b6aee5ba52a4c83979935b063239505166ce68e87dac7a0a6a4ca7e849a4a406977d31614f161b347d4e8a5eaa9",
          "sha256": "e575d2a0b72171ceff6161104c21433c5b7fb6c8afea5a1de23944de31c04811",
          "sha1": "60ca1285f3b44a9a010bf42911fdd179af427ed6",
          "md5": "11e045374bdd6550450ce822a698f184"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "dev.icerock.moko",
          "module": "parcelize",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.tmapps",
          "module": "konnection",
          "version": {
            "requires": "1.1.10"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "cupertino-adaptive",
          "version": {
            "requires": "0.1.0-alpha04"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.1-DEV-SNAPSHOT.kotlin_resources.zip",
          "url": "sdk-iosarm64-1.0.1-DEV-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 29587,
          "sha512": "bdffc6d1b8d5c537a86c343f796d85355601545d1b48b6388a15574da9c3550e7a1bad9e97f4abc9e39424a9d296b103ece86f7f3c360b4887007366f3fb8c3b",
          "sha256": "a5acbcfa2b69dc7b0066193b382148d3cb98dc3329edc50e9901a466c75a3ab4",
          "sha1": "0f795f7c1c00fe1584be97a711c756046a55bc2e",
          "md5": "a3b0b39008e00cf8451a7191f3c44e6d"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "dev.icerock.moko",
          "module": "parcelize",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.tmapps",
          "module": "konnection",
          "version": {
            "requires": "1.1.10"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "cupertino-adaptive",
          "version": {
            "requires": "0.1.0-alpha04"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-iosarm64-1.0.1-DEV-SNAPSHOT-metadata.jar",
          "url": "sdk-iosarm64-1.0.1-DEV-SNAPSHOT-metadata.jar",
          "size": 18497,
          "sha512": "0a50228c8cfa905edd3806a8cba9e9b076cd1d2011d4867597eb66af82006f45b62e04a5bf9287f9caf007b963805f75fd575b9eb044c1d9d64ecddfe2e0a0b3",
          "sha256": "24ce9b4b4d9662585d42942bd1ba1a40a0fa182377bc8184c87e8b204762b1b2",
          "sha1": "885a46c459bb24e12c5450412d2ef926754f6036",
          "md5": "48a02c0233ae4f7863cc64d306b65af7"
        }
      ]
    }
  ]
}
