{
  "formatVersion": "1.1",
  "component": {
    "group": "com.accesspaysuite.mobilesdk",
    "module": "sdk",
    "version": "1.0.1-DEV-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "dev.icerock.moko",
          "module": "parcelize",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.tmapps",
          "module": "konnection",
          "version": {
            "requires": "1.1.10"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "cupertino-adaptive",
          "version": {
            "requires": "0.1.0-alpha04"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-metadata-1.0.1-DEV-SNAPSHOT.jar",
          "url": "sdk-1.0.1-DEV-SNAPSHOT.jar",
          "size": 120079,
          "sha512": "5daea7a2d855712b60b85e2c071e588849ecb6619593c916e5f14eadeb69bc0b87c99acc7d5c64b574c30c92b0b9ef3668390b905a71bd9a25f1fa1ef27021e2",
          "sha256": "4531a900f05b4d07f21b281eaedea44c9b34267809f3bf39d28194c580518b4f",
          "sha1": "f474d9ee835f65a1339420262d73ed0e328aba06",
          "md5": "805e48fcd6f00fad660752a2bd7bc17e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "sdk-kotlin-1.0.1-DEV-SNAPSHOT-sources.jar",
          "url": "sdk-1.0.1-DEV-SNAPSHOT-sources.jar",
          "size": 147589,
          "sha512": "12a5c0a1b9573a4cc8d74e745abc1d274e44333d9931fc994d64ad883e2d398409d83f70918a717f2fe9e322083c3c94cee24ed1c99ec670fa48e4642f31e493",
          "sha256": "a35355a2824ccf2976cff9659f84524e46dcd759699cf7e2cf0b03ea275409fc",
          "sha1": "9ebaf6867ef283dfb417a68b46a1e31904a34da2",
          "md5": "426fc2282d5731ef73f92baf05c13c24"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-android/1.0.1-DEV-SNAPSHOT/sdk-android-1.0.1-DEV-SNAPSHOT.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-android",
        "version": "1.0.1-DEV-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-android/1.0.1-DEV-SNAPSHOT/sdk-android-1.0.1-DEV-SNAPSHOT.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-android",
        "version": "1.0.1-DEV-SNAPSHOT"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-android/1.0.1-DEV-SNAPSHOT/sdk-android-1.0.1-DEV-SNAPSHOT.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-android",
        "version": "1.0.1-DEV-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosarm64/1.0.1-DEV-SNAPSHOT/sdk-iosarm64-1.0.1-DEV-SNAPSHOT.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iosarm64",
        "version": "1.0.1-DEV-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosarm64/1.0.1-DEV-SNAPSHOT/sdk-iosarm64-1.0.1-DEV-SNAPSHOT.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iosarm64",
        "version": "1.0.1-DEV-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosarm64/1.0.1-DEV-SNAPSHOT/sdk-iosarm64-1.0.1-DEV-SNAPSHOT.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iosarm64",
        "version": "1.0.1-DEV-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosarm64/1.0.1-DEV-SNAPSHOT/sdk-iosarm64-1.0.1-DEV-SNAPSHOT.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iosarm64",
        "version": "1.0.1-DEV-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iossimulatorarm64/1.0.1-DEV-SNAPSHOT/sdk-iossimulatorarm64-1.0.1-DEV-SNAPSHOT.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iossimulatorarm64",
        "version": "1.0.1-DEV-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iossimulatorarm64/1.0.1-DEV-SNAPSHOT/sdk-iossimulatorarm64-1.0.1-DEV-SNAPSHOT.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iossimulatorarm64",
        "version": "1.0.1-DEV-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iossimulatorarm64/1.0.1-DEV-SNAPSHOT/sdk-iossimulatorarm64-1.0.1-DEV-SNAPSHOT.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iossimulatorarm64",
        "version": "1.0.1-DEV-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iossimulatorarm64/1.0.1-DEV-SNAPSHOT/sdk-iossimulatorarm64-1.0.1-DEV-SNAPSHOT.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iossimulatorarm64",
        "version": "1.0.1-DEV-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosx64/1.0.1-DEV-SNAPSHOT/sdk-iosx64-1.0.1-DEV-SNAPSHOT.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iosx64",
        "version": "1.0.1-DEV-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosx64/1.0.1-DEV-SNAPSHOT/sdk-iosx64-1.0.1-DEV-SNAPSHOT.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iosx64",
        "version": "1.0.1-DEV-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosx64/1.0.1-DEV-SNAPSHOT/sdk-iosx64-1.0.1-DEV-SNAPSHOT.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iosx64",
        "version": "1.0.1-DEV-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosx64/1.0.1-DEV-SNAPSHOT/sdk-iosx64-1.0.1-DEV-SNAPSHOT.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iosx64",
        "version": "1.0.1-DEV-SNAPSHOT"
      }
    }
  ]
}
