{
  "formatVersion": "1.1",
  "component": {
    "group": "com.accesspaysuite",
    "module": "mobilesdk",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "dev.icerock.moko",
          "module": "parcelize",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.tmapps",
          "module": "konnection",
          "version": {
            "requires": "1.1.10"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "cupertino-adaptive",
          "version": {
            "requires": "0.1.0-alpha04"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobilesdk-1.0.1.jar",
          "url": "mobilesdk-1.0.1.jar",
          "size": 120657,
          "sha512": "3e20819c165dd3a45f2f6749fac86cd2f34b21235c2d232f89cef7f5df5a044477cfd0b6b987c308f391215ae00b21dbe83518750ec3d3effde5a7d176e5308d",
          "sha256": "925b8fe253b67c7700763a26b8f38f3ef59ab7504f76774e931a3839aba1b389",
          "sha1": "e94c480a1cb13b515b8cb1a36407fa4115fdfda5",
          "md5": "2020f2f84dba9336852adf408bcaca6f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "mobilesdk-1.0.1-sources.jar",
          "url": "mobilesdk-1.0.1-sources.jar",
          "size": 149713,
          "sha512": "37508bdeee34cbb5dcc47b499e5b3f0504381080ef7d24be4306ac03f865c76b44bddd3da701dd945cf7129e0ae63fdf06431eb4c50be52042f811491eb36bc8",
          "sha256": "5469e73c74859b36e63c6e94f779468b009c54a33f8cb1adcc6ec3136f78a019",
          "sha1": "fbccd11b6a6fb558331521b4cfcdb04cadbe7e29",
          "md5": "ab45fbdc3ba8d0b135e650727323dbca"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-android/1.0.1/sdk-android-1.0.1.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-android",
        "version": "1.0.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-android/1.0.1/sdk-android-1.0.1.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-android",
        "version": "1.0.1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-android/1.0.1/sdk-android-1.0.1.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-android",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosarm64/1.0.1/sdk-iosarm64-1.0.1.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iosarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosarm64/1.0.1/sdk-iosarm64-1.0.1.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iosarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosarm64/1.0.1/sdk-iosarm64-1.0.1.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iosarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosarm64/1.0.1/sdk-iosarm64-1.0.1.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iosarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iossimulatorarm64/1.0.1/sdk-iossimulatorarm64-1.0.1.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iossimulatorarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iossimulatorarm64/1.0.1/sdk-iossimulatorarm64-1.0.1.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iossimulatorarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iossimulatorarm64/1.0.1/sdk-iossimulatorarm64-1.0.1.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iossimulatorarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iossimulatorarm64/1.0.1/sdk-iossimulatorarm64-1.0.1.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iossimulatorarm64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosx64/1.0.1/sdk-iosx64-1.0.1.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iosx64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosx64/1.0.1/sdk-iosx64-1.0.1.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iosx64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosx64/1.0.1/sdk-iosx64-1.0.1.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iosx64",
        "version": "1.0.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../sdk-iosx64/1.0.1/sdk-iosx64-1.0.1.module",
        "group": "com.accesspaysuite.mobilesdk",
        "module": "sdk-iosx64",
        "version": "1.0.1"
      }
    }
  ]
}
