{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/1.0.1-SNAPSHOT/sdk-1.0.1-SNAPSHOT.module",
    "group": "com.accesspaysuite.mobilesdk",
    "module": "sdk",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "dev.icerock.moko",
          "module": "parcelize",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.tmapps",
          "module": "konnection",
          "version": {
            "requires": "1.1.10"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "cupertino-adaptive",
          "version": {
            "requires": "0.1.0-alpha04"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-iosArm64Main-1.0.1-SNAPSHOT.klib",
          "url": "sdk-iosarm64-1.0.1-SNAPSHOT.klib",
          "size": 1054843,
          "sha512": "802fe8172939124031e41ff2864a2fceddf8a1445b1534683b4415c8a2082780581a2db37ecf7100061c4d57a659dd482ea2ff86cbcca67f4173c06d1dac6eb0",
          "sha256": "8210537b52432282552d0b8a2c8b831d9cb0b884be84813631197e56a3e3b41f",
          "sha1": "4956be6d1092358026b1999f995d29d608f63dcc",
          "md5": "74900b5a3bf9e673079f6a831fe4b494"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "sdk-iosarm64-1.0.1-SNAPSHOT-sources.jar",
          "url": "sdk-iosarm64-1.0.1-SNAPSHOT-sources.jar",
          "size": 149288,
          "sha512": "9a9c59a3a355faef8846952fdb0d9eb425da4c2e245b5ecc5958015cbb67e9598a3147544c9a99207f12aa346957510e528d8a3e3a421504fa520f9b8ae27667",
          "sha256": "15ff58927c2c5f80bd5d5a856121d0689ea88ef5626ec2e0881ac5d8c22c3682",
          "sha1": "95aaa60a4ded8b39408dfdca543d2ec75a886192",
          "md5": "26c0c99049cef70a9b8aaf50558e2825"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "dev.icerock.moko",
          "module": "parcelize",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.tmapps",
          "module": "konnection",
          "version": {
            "requires": "1.1.10"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "cupertino-adaptive",
          "version": {
            "requires": "0.1.0-alpha04"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.1-SNAPSHOT.kotlin_resources.zip",
          "url": "sdk-iosarm64-1.0.1-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 29587,
          "sha512": "bdffc6d1b8d5c537a86c343f796d85355601545d1b48b6388a15574da9c3550e7a1bad9e97f4abc9e39424a9d296b103ece86f7f3c360b4887007366f3fb8c3b",
          "sha256": "a5acbcfa2b69dc7b0066193b382148d3cb98dc3329edc50e9901a466c75a3ab4",
          "sha1": "0f795f7c1c00fe1584be97a711c756046a55bc2e",
          "md5": "a3b0b39008e00cf8451a7191f3c44e6d"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "dev.icerock.moko",
          "module": "parcelize",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.tmapps",
          "module": "konnection",
          "version": {
            "requires": "1.1.10"
          }
        },
        {
          "group": "io.github.alexzhirkevich",
          "module": "cupertino-adaptive",
          "version": {
            "requires": "0.1.0-alpha04"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-ktor",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.0.0-alpha08"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-iosarm64-1.0.1-SNAPSHOT-metadata.jar",
          "url": "sdk-iosarm64-1.0.1-SNAPSHOT-metadata.jar",
          "size": 18497,
          "sha512": "704717f003958a5d65b7fee7b0ce02bf3ab2f553bca15b201ca710fc409734679410fa2edf15cdee545dd81a30d3dd9fd1b8e92e3b068b257f6ba257fd261ea1",
          "sha256": "9621be574c54a4fda9feb30a3421460414c831ef75bdfcd2de42e33d48ba8708",
          "sha1": "ede2e1b996d113e280a4c0a6795bc6dcc21b88b6",
          "md5": "0988d74ab7d64f585dd6d282cf273b1e"
        }
      ]
    }
  ]
}
